### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [ItsMerkz/Tellonym.me-Account-Creator#1]
its so slow and u should atleast add email verif using mail.gw

**Comment by ghost** [comment]
crashes after 2 accounts are genned btw

**Comment by ItsMerkz** [comment]
don't crash for me so idk why that happened also... im not gonna email verify because its not needed right now until tellonyme start locking accounts i will leave it unverified

**Comment by ghost** [comment]
> don't crash for me so idk why that happened also... im not gonna email verify because its not needed right now until tellonyme start locking accounts i will leave it unverified

but why is it like 500 accounts an hour

**Comment by ghost** [comment]
also u should make a account checker for this lmao

**Comment by ItsMerkz** [comment]
okay, firstly its slow because of threading and captcha, which i will add a captcha solver to it, and yeah follow bot and checker will probs be added tmrw lol, might make a multi tool so you can do loads, but defo some stuff added tmrw dw ty for the suggestion

**Comment by ghost** [comment]
> okay, firstly its slow because of threading and captcha, which i will add a captcha solver to it, and yeah follow bot and checker will probs be added tmrw lol, might make a multi tool so you can do loads, but defo some stuff added tmrw dw ty for the suggestion

1 month later no update
