### ISSUE TITLE
Can you make a requirements.txt?

### ISSUE THREAD

**Issue by Zoult** [ItsMerkz/Tellonym.me-Account-Creator#2]

**Comment by ItsMerkz** [comment]
yeah, sure i will add it in a minute

**Comment by ItsMerkz** [comment]
done, check now

**Comment by nostorian** [comment]
> I do not know Python, when i try do install the dependencies it says that "string" is not a package. Idk, can you do a requirements.txt file?

skill issue

**Comment by nostorian** [comment]
like literally its just 3 dependencies and those are common af
