### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by clipssender31** [ItsMerkz/Tellonym.me-Account-Creator#4]
hi, my one is faster :(

**Comment by ItsMerkz** [comment]
used all my headers, used my client, lol i see the captcha code is from tokens404 joiner, i see the threading is from Oxi's old discord gen, lol, sad you had to say that, you gave me a reason to call you out lol, also, heres a tip - make your async, and thread it with a pool, you will make hundreds in seconds lol :D

**Comment by clipssender31** [comment]
> used all my headers, used my client, lol i see the captcha code is from tokens404 joiner, i see the threading is from Oxi's old discord gen, lol, sad you had to say that, you gave me a reason to call you out lol, also, heres a tip - make your async, and thread it with a pool, you will make hundreds in seconds lol :D

* Did not use your headers, used what I thought would be best.
* Used your "client"? lmao makes zero sense
* Did not use the "captcha code" from tokens404 joiner, i've never heard of that joiner before lol. I have been using the captchatools lib for a quite a long time.
* I'm using ThreadPoolExecutor to thread it. I dont see how that is using the same threading from "Oxi's old discord gen".

**Comment by ItsMerkz** [comment]
I mean the fact you completely skidded your token joiner from shahzain makes me think otherwise 💀
